CREATE TABLE image_links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_id INT NOT NULL,
  owner_type VARCHAR(50) NOT NULL,
  owner_id INT NOT NULL,
  tag VARCHAR(50),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_image FOREIGN KEY (image_id) REFERENCES Images(id) ON DELETE CASCADE
);